parameters:
    autotext.service.class:   AutotextBundle\Service\AutotextService

services:
    service.autotext:
        class:     "%autotext.service.class%"
        arguments: [ "@service_container" ]

