parameters:
    autotext.service.class:   AutotextBundle\Service\AutotextService
    autotext.twig.extension.class:   AutotextBundle\Twig\AutotextExtension

services:
    service.autotext:
        class:     "%autotext.service.class%"
        arguments: [ "@service_container" ]
    twig.autotext:
        class:     "%autotext.twig.extension.class%"
        public:    false
        tags:
            - { name: twig.extension }
